### ISSUE TITLE
Mention in the docs that you discard the internal subset, if one exists

### ISSUE THREAD

**Issue by dwcramer** [AndrewSales/doctype-tool#1]
Thanks for creating this handy tool. Maybe mention in the readme and/or wiki that it doesn't keep the internal subset when you modify something. For example, in the following `[<!ENTITY foo "foobar">]` is discarded. 
```
<!DOCTYPE html
  SYSTEM "about:legacy-compat" [
        <!ENTITY foo "foobar">
]>
```
If you could enhance it to preserve the internal subset unchanged, that would be great too but I understand if that's not in scope.

**Comment by AndrewSales** [comment]
Many thanks for your feedback, @dwcramer .
I've updated [the wiki](https://github.com/AndrewSales/doctype-tool/wiki/Getting-started#internal-subset) as you suggest, and opened #2 for this enhancement.
